function init(self)
	msg.post("#", "blink_on")
end

function on_message(self, message_id, message, sender)
	if message_id == hash("blink_on") then
		msg.post("#sprite", "enable")
		timer.seconds(math.random(15, 30), function()
			msg.post("#", "blink_off")
		end)
	elseif message_id == hash("blink_off") then
		msg.post("#sprite", "disable")
		timer.seconds(math.random(1, 2) / 10, function()
			msg.post("#", "blink_on")
		end)
	end
end
